### ISSUE TITLE
CRUDnoticia.php

### ISSUE THREAD

**Issue by agarpac** [agarpac/pa-proyecto-2016#17]

**Comment by rmonrec** [comment]
@fmaraque @agarpac Acabo de hacer el commit, ademas de crear las crud de noticia, he editado una función de CRUDUsuario, que no cerraba la conexión a la base de datos, he añadido el campo 'titular_noticia' a la tabla de noticia, y he editado la visualización de los equipos en el registro añadiéndole espacios entre los radiobutton.
Perdón por no haberme cambiado de rama y demás, las prisas son malas... no volverá a pasar.
PD: FELIZ AÑO NUEVO A LOS DOS!! :)
