### ISSUE TITLE
header.php

### ISSUE THREAD

**Issue by agarpac** [agarpac/pa-proyecto-2016#2]

**Comment by fmaraque** [comment]
El header he pensado en hacerlo comun para admin y user. Cómo lo veis @agarpac @rmonrec  ?

**Comment by agarpac** [comment]
@fmaraque Yo lo veo común. Las funcionalidades extras del admin, lo veo mejor en el indexAdminitrador.php directamente, antes que en un header aparte.

**Comment by fmaraque** [comment]
Lo he hecho en el mismo header.php. Comprueba con la variable sesion si es user o admin y muestra una u otras opciones. Creo que nos va a ser más fácil de trabajar así (estilos, redirecciones y demás). Echadle un ojo cuando me acepteis el PR y me deciis. @agarpac @rmonrec
