### ISSUE TITLE
Validar login

### ISSUE THREAD

**Issue by agarpac** [agarpac/pa-proyecto-2016#31]

**Comment by agarpac** [comment]
@fmaraque me la asigno para retocar el estilo de la validación

**Comment by agarpac** [comment]
@fmaraque Mi parte ha acabado. Te lo dejo asignado y en WIP para que reviese los 3 ifs que están ahora mismo comentados en el código:

if ($("#userError").length !== 0) 

Por lo que observo simplemente debe ser un copy paste (porque los 3 son iguales) de cuando estuviste empezando a pensar como hacerlo, pero realmente no sirven para nada.

**Comment by fmaraque** [comment]
@agarpac ahora mismo se están validando de dos maneras. Una insertando texto en el input de pass y user y otra con un texto rojo. Dime cual dejamos y borro la otra validacion

**Comment by agarpac** [comment]
Mañana por la mañana reviso ésto sin falta. @fmaraque

**Comment by agarpac** [comment]
@fmaraque Yo quitaría los textos rojos que aparecen y dejaría lo que se crea dentro de los input

**Comment by fmaraque** [comment]
Perfecto @agarpac , mañana a primera hora me encargo de eliminar los rojos

**Comment by fmaraque** [comment]
@agarpac Limpiado los errores en la validacion. Ahora se comprueba que el campo user no esté vacio y que cumpla con la expresion regular de mail. Para el campo pass comprueba que el campo no esté vacio.

La pongo a closed y done
