### ISSUE TITLE
Inhabilitar accesos [Mirar descripción]

### ISSUE THREAD

**Issue by agarpac** [agarpac/pa-proyecto-2016#43]
No dejar acceder directamente por URL a usuarios no logueados a las siguientes páginas:

- inicio.php
- partidos.php
- mensajes.php
- amigos.php
- noticias.php
- equipos.php
- ...

En resumen, solo pueden acceder a las págs de información genéricas, las que están situadas en el footer.

**Comment by fmaraque** [comment]
Está hecho para lo que tenemos desarrollado y finalizado (inicio, adminnoticias, modificarnoticias...). La idea es que cada vez que  nos pongamos con una pagina nueva, añadir eso.

**Comment by rmonrec** [comment]
Está en todas las paginas, excepto en aquellas en las que aun no tiene el diseño, como modificar noticia por ejemplo
