### ISSUE TITLE
noticias.php

### ISSUE THREAD

**Issue by agarpac** [agarpac/pa-proyecto-2016#5]

**Comment by fmaraque** [comment]
No sé por qué no funciona el update. Podéis echarle un ojo? @agarpac @rmonrec

**Comment by agarpac** [comment]
@rmonrec te la asigno para que revises cuando puedas lo del update que comenta @fmaraque

**Comment by rmonrec** [comment]
@fmaraque @agarpac me pongo a ello, a ver que veo

**Comment by rmonrec** [comment]
ARREGLADO! 👍
