### ISSUE TITLE
crear DataBase

### ISSUE THREAD

**Issue by agarpac** [agarpac/pa-proyecto-2016#6]

**Comment by fmaraque** [comment]
Como está acabada. La pongo a close. Si por casualidad vemos que hay que cambiar algo, pues ya vemos qué hacemos

**Comment by agarpac** [comment]
@fmaraque @rmonrec Si hay que reabrir una tarea para añadir cosas y/o arreglarla, la podemos reabrir y pasar a WIP y cambiar la label a "bug" o "enchancement" según el caso.
Al menos así lo veo que queda más claro!

**Comment by fmaraque** [comment]
Perfecto!
